# Generated by Django 4.0.5 on 2022-06-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='animation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animations.animation'),
            preserve_default=False,
        ),
    ]
